# Generated by Django 4.1.4 on 2023-01-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('video_url', models.URLField(max_length=9999999999999999999999999999999999999999999999999999999999999999999)),
            ],
        ),
    ]
