# Generated by Django 4.1.4 on 2022-12-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('video_url', models.URLField(help_text='Enter your url here..', max_length=100000000000000000000000000000)),
            ],
        ),
    ]
