# Generated by Django 4.1.4 on 2022-12-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(default='', help_text='Enter here..', max_length=100000000),
        ),
    ]
